name: Convert ReadMe (Markdown) to HTML

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run convert
    - name: Possibly commit HTML changes
      run: |
        if [[ `git status --porcelain` ]]; then
          git config --global user.name 'JZEL Bot'
          git config --global user.email 'jo.zeller@protonmail.com'
          git add -A
          git commit -m "Automatically update HTML according to ReadMe"
          git push
        fi
